// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRkFmv43pKk0wiSWLayYCkcx7kt8Fn_lY',
    appId: '1:494373017938:web:a08f597c74db27c5af028b',
    messagingSenderId: '494373017938',
    projectId: 'rdpprojecttodolist',
    authDomain: 'rdpprojecttodolist.firebaseapp.com',
    storageBucket: 'rdpprojecttodolist.appspot.com',
    measurementId: 'G-S43PTSZXHS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrjI6gU-QmhydwV3RVksEw7Clm2bF76Pc',
    appId: '1:494373017938:android:f292f6cadae26a76af028b',
    messagingSenderId: '494373017938',
    projectId: 'rdpprojecttodolist',
    storageBucket: 'rdpprojecttodolist.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMYmRkC-xcd3weMDZnCAkGYcd7M_T5J3k',
    appId: '1:494373017938:ios:3a01bd8e6b180c73af028b',
    messagingSenderId: '494373017938',
    projectId: 'rdpprojecttodolist',
    storageBucket: 'rdpprojecttodolist.appspot.com',
    iosBundleId: 'com.example.rdptodolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMYmRkC-xcd3weMDZnCAkGYcd7M_T5J3k',
    appId: '1:494373017938:ios:3a01bd8e6b180c73af028b',
    messagingSenderId: '494373017938',
    projectId: 'rdpprojecttodolist',
    storageBucket: 'rdpprojecttodolist.appspot.com',
    iosBundleId: 'com.example.rdptodolist',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRkFmv43pKk0wiSWLayYCkcx7kt8Fn_lY',
    appId: '1:494373017938:web:2e587883b1b33ee0af028b',
    messagingSenderId: '494373017938',
    projectId: 'rdpprojecttodolist',
    authDomain: 'rdpprojecttodolist.firebaseapp.com',
    storageBucket: 'rdpprojecttodolist.appspot.com',
    measurementId: 'G-QQQQ01LSYM',
  );
}
